config/routes.rb
Rails.application.routes.draw do
  
  get 'users/account'
  get 'users/profile'
  get 'pages/home'
  get 'pages/tokyo'
  get 'pages/kyoto'
  get 'pages/osaka'
  get 'pages/sapporo'
  get 'pages/account'
  get 'pages/profile'
  get 'search' => "pages#search"
  get 'rooms/own'
  
  
  resources :reservations do
    member do
      post 'confirm' => 'reservations#confirm'
      post 'back'
    end
  end

  root 'pages#home'
  
  devise_for :users
  resources :rooms  
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
 belongs_to :user
 belongs_to :room
 
 validates :start_date, presence: true
 validates :end_date, presence: true
 validates :total_people, presence: true
 validate :valid_eligiblity_range?
 validate :pretend_ago

def pretend_ago
    today = Date.today
    
    return unless start_date? && today
    
    if !start_date.after?(today)
    errors.add(:start_date, 'must be after Today')
    end
end

def valid_eligiblity_range?
    return unless end_date? && start_date?

    if !end_date.after?(start_date)
      errors.add(:start_date, "must be before Expiration Date")
      errors.add(:end_date, "must be after Start Date")
    end
end
    
 def sum_of_days
  (end_date.to_date - start_date.to_date).to_i
 end

 def sum_of_price
  (room.fee * total_people * sum_of_days).to_i
 end
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :reservations
  
  mount_uploader :image, ImagesUploader
  
  validates :title, presence: true
  validates :content, presence: true
  validates :fee, presence: true
  validates :address, presence: true
  
  def self.search(search)
    if search != ""
      Room.where('title LIKE(?) OR content LIKE(?)', "%#{params[:title]}%", "%#{params[:content]}%")
    else
      Room.all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :rooms
  has_many :reservations
  
  mount_uploader :avator, ImagesUploader
  
  validates :name, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?
    
    protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
        devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile])
    end
    
    private
    def after_sign_in_path_for(resource)
        root_path
    end

    def after_sign_out_path_for(resource)
        root_path 
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def search
    if params[:address].present?
      @rooms = Room.where('address LIKE ?', "%#{params[:address]}%")
    else
      @rooms = Room.all
    end
  end
  
  def tokyo
      @rooms = Room.where('address LIKE ?', "%東京%")
  end
  
  def kyoto
      @rooms = Room.where('address LIKE ?', "%京都%")
  end
  
  def osaka
      @rooms = Room.where('address LIKE ?', "%大阪%")
  end
  
  def sapporo
      @rooms = Room.where('address LIKE ?', "%札幌%")
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  def confirm
    @reservation = Reservation.new(params.permit(:start_date, :end_date, :total_people, :total_day, :total_fee, :room_id, :user_id))

    @room = Room.find(params[:room_id])
    @user = User.find(current_user.id)
    @user_id = current_user.id
    
    @reservation.total_day = @reservation.sum_of_days
    @reservation.total_fee = @reservation.sum_of_price
    
  end


  def create
    @reservation = Reservation.new(params.require(:reservation).permit(:start_date, :end_date, :total_people, :total_day, :total_fee, :room_id, :user_id))
    @room = @reservation.room
    @reservation.total_fee = @reservation.sum_of_price
    @user = User.find(current_user.id)
    @user_id = current_user.id

    
    if @reservation.save
      flash[:success] = "予約しました"
      redirect_to controller: :reservations, action: :index
    else
      render "confirm"
    end
  end

  def index
    @reservations = current_user.reservations.all
  end
  
  def edit
    @reservation = Reservation.find(params[:id])
  end
  
  def update
    @reservation = Reservation.find(params[:id])

    if @reservation.update(reservation_params)
      flash[:notice] = "保存しました。"
      redirect_to controller: :reservations, action: :confirm
    else
      flash[:alert] = "問題が発生しました。"
      render "edit"
    end
  end
  
  def destroy
     @reservation = Reservation.find(params[:id])
     @reservation.destroy
     flash[:notice] = "ユーザーを削除しました"
     redirect_to controller: :reservations, action: :index
  end
  
private
  def reservation_params
        params.permit(:start_date, :end_date, :total_people, :total_day, :total_fee, :room_id, :user_id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  def new
    @room = Room.new
  end
  
  def create
    @room = Room.new(room_params)
    @room.user_id = current_user.id

    if @room.save
      flash[:success] = "施設の登録に成功しました"
      redirect_to controller: :rooms, action: :show, id: @room.id
    else
      flash[:alert] = "登録に失敗しました"
      render :new
    end
  end

  def show
    @room = Room.find(params[:id])
    @user = User.find(current_user.id)

    @reservations = Reservation.new
  end

  def own
    @rooms = current_user.rooms.all
  end
  
  def index
    @rooms = Room.where('address LIKE(?)',"%#{params[:address]}%")
   if params[:keyword].present?
    @rooms = Room.where([ 'content LIKE ? OR title LIKE ? ',"%#{params[:keyword]}%","%#{params[:keyword]}%" ])
   end
  end
  
  def edit
    @room = Room.find(params[:id])
  end
  
  def update
    @room = Room.find(params[:id])
    @room.user_id = current_user.id
    
    if @room.update(room_params)
      flash[:notice] = "保存しました。"
      redirect_to controller: :rooms, action: :show, id: @room.id
    else
      flash[:alert] = "問題が発生しました。"
      render "edit"
    end
  end
  
  def destroy
     @room = Room.find(params[:id])
     @room.destroy
     flash[:notice] = "ユーザーを削除しました"
     redirect_to :rooms
  end
  
  private
    def room_params
      params.require(:room).permit(:title, :content, :fee, :address, :image)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def account
    @user = User.find(current_user.id)  

  end

  def profile
    @user = User.find(current_user.id)  
  end
  
  def edit
    @user = User.find(current_user.id)  
  end
  
  def update
    @user = User.find(current_user.id)
    if @user.update(params.require(:user).permit(:name, :avator, :profile))
      flash[:notice] = "保存しました。"
      redirect_to users_profile_path
    else
      flash[:alert] = "問題が発生しました。"
      render "edit"
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class = "error">
     <ul>
        <% model.errors.full_messages.each do |message| %>
           <li><%= message %></li>
	    <% end %>
     </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<%= render "shared/navbar" %>

<section class="top-section">
    <div class="top-content">
        <h2>Potepan Shareで</br>まだ体験したことのない</br>旅をしよう</h2>
    </div>
    <div class="top-form">
    <%= form_with url: search_path, local: true, method: :get do |f|%>
    <%= f.text_field :address %>
    <%= f.submit "検索"%>
    <% end %>
    </div>
</section>
<section class="area-section">
    <h2>おすすめエリア</h2>
    <div class="area">
        <%= link_to "東京", pages_tokyo_path, class:"area_tokyo"%>
        <%= link_to "京都", pages_kyoto_path, class:"area_kyoto" %>
        <%= link_to "大阪", pages_osaka_path, class:"area_osaka" %>
        <%= link_to "札幌", pages_sapporo_path, class:"area_sapporo" %>
    </div>
</section>

<%= render "shared/footer"%>

app/views/pages/kyoto.html.erb
<%= render "shared/navbar" %>
<%= render "shared/area"%>
<div class="count">
    <p><%= @rooms.count %>件が見つかりました</p>
</div>
<% @rooms.each do |room| %>

 <table class="show-table">
   <tr>
     <th>施設名</th>
     <td><%=link_to room.title, room_path(room.id) %></td>
   </tr>
   <tr>
     <th>住所</th>
     <td><%= room.address %></td>
   </tr>
   <tr>
     <th>施設詳細</th>
     <td><%= room.content %></td>
   </tr>
   <tr>
     <th>料金</th>
     <td><%= room.fee %></td>
   </tr>
     <th>画像</th>
     <td><%= image_tag room.image.to_s %></td>
   </tr>
    <tr>
     <th></th>
     <td><%=link_to "詳細はこちら", room_path(room.id) %></td>
   <tr>
 </table>
<% end %>
<%= render "shared/footer"%>

app/views/pages/osaka.html.erb
<%= render "shared/navbar" %>
<%= render "shared/area"%>
<div class="count">
    <p><%= @rooms.count %>件が見つかりました</p>
</div>
<% @rooms.each do |room| %>

 <table class="show-table">
   <tr>
     <th>施設名</th>
     <td><%=link_to room.title, room_path(room.id) %></td>
   </tr>
   <tr>
     <th>住所</th>
     <td><%= room.address %></td>
   </tr>
   <tr>
     <th>施設詳細</th>
     <td><%= room.content %></td>
   </tr>
   <tr>
     <th>料金</th>
     <td><%= room.fee %></td>
   </tr>
     <th>画像</th>
     <td><%= image_tag room.image.to_s %></td>
   </tr>
    <tr>
     <th></th>
     <td><%=link_to "詳細はこちら", room_path(room.id) %></td>
   <tr>
 </table>
<% end %>
<%= render "shared/footer"%>

app/views/pages/sapporo.html.erb
<%= render "shared/navbar" %>
<%= render "shared/area"%>
<div class="count">
    <p><%= @rooms.count %>件が見つかりました</p>
</div>
<% @rooms.each do |room| %>

 <table class="show-table">
   <tr>
     <th>施設名</th>
     <td><%=link_to room.title, room_path(room.id) %></td>
   </tr>
   <tr>
     <th>住所</th>
     <td><%= room.address %></td>
   </tr>
   <tr>
     <th>施設詳細</th>
     <td><%= room.content %></td>
   </tr>
   <tr>
     <th>料金</th>
     <td><%= room.fee %></td>
   </tr>
     <th>画像</th>
     <td><%= image_tag room.image.to_s %></td>
   </tr>
    <tr>
     <th></th>
     <td><%=link_to "詳細はこちら", room_path(room.id) %></td>
   <tr>
 </table>
<% end %>
<%= render "shared/footer"%>

app/views/pages/search.html.erb
<%= render "shared/navbar" %>
<%= render "shared/area"%>
<div class="count">
    <p><%= @rooms.count %>件が見つかりました</p>
</div>
<% @rooms.each do |room| %>

 <table class="show-table">
   <tr>
     <th>施設名</th>
     <td><%= room.title %></td>
   </tr>
   <tr>
     <th>住所</th>
     <td><%= room.address %></td>
   </tr>
   <tr>
     <th>施設詳細</th>
     <td><%= room.content %></td>
   </tr>
   <tr>
     <th>料金</th>
     <td><%= room.fee %></td>
   </tr>
     <th>画像</th>
     <td><%= image_tag room.image.to_s %></td>
   </tr>
    <tr>
     <th></th>
     <td><%=link_to "詳細はこちら", room_path(room.id) %></td>
   <tr>
 </table>
<% end %>
<%= render "shared/footer"%>

app/views/pages/tokyo.html.erb
<%= render "shared/navbar" %>
<%= render "shared/area"%>
<div class="count">
    <p><%= @rooms.count %>件が見つかりました</p>
</div>
<% @rooms.each do |room| %>

 <table class="show-table">
   <tr>
     <th>施設名</th>
     <td><%=link_to room.title, room_path(room.id) %></td>
   </tr>
   <tr>
     <th>住所</th>
     <td><%= room.address %></td>
   </tr>
   <tr>
     <th>施設詳細</th>
     <td><%= room.content %></td>
   </tr>
   <tr>
     <th>料金</th>
     <td><%= room.fee %></td>
   </tr>
     <th>画像</th>
     <td><%= image_tag room.image.to_s %></td>
   </tr>
    <tr>
     <th></th>
     <td><%=link_to "詳細はこちら", room_path(room.id) %></td>
   <tr>
 </table>
<% end %>
<%= render "shared/footer"%>

app/views/reservations/_form.html.erb
<h1>予約フォーム</h1>
<%= form_with model:@reservation, local: true, url: confirm_reservation_path do |f| %>
	
	<dl>
		<dt>チェックイン</dt>
		<dd><%= f.date_field :start_date %></dd>
		<dt>チェックアウト</dt>
		<dd><%= f.date_field :end_date %></dd>
		<dt>人数</dt>
		<dd><%= f.number_field :total_people %></dd>
	</dl>

	<%= f.submit '確認画面へ' %>
<% end %>

app/views/reservations/confirm.html.erb
<h1>予約内容の確認</h1>

 <table class="show-table">
   <tr>
     <th>チェックイン</th>
     <td><%= @reservation.start_date.to_s(:datetime_jp) %></td>
   </tr>
   <tr>
     <th>チェックアウト</th>
     <td><%=@reservation.end_date.to_s(:datetime_jp) %></td>
   </tr>
   <tr>
     <th>人数</th>
     <td><%= @reservation.total_people %></td>
   </tr>
   <tr>
     <th>宿泊日数</th>
     <td><%= @reservation.total_day %></td>
   </tr>
   <tr>
     <th>お支払い金額</th>
     <td><%= @reservation.total_fee %></td>
   </tr>
 </table>

<%=link_to '戻る', :back%>

<%= form_with model: @reservation, local: true do |f| %>
	<%= f.hidden_field :start_date %>
	<%= f.hidden_field :end_date %>
	<%= f.hidden_field :total_people %>
    <%= f.hidden_field :user_id, value: @user.id %>
    <%= f.hidden_field :room_id, value: @room.id%>
	<%= f.submit '送信する' %>
<% end %>

<%= render "shared/footer"%>

app/views/reservations/index.html.erb
<%= render  "shared/navbar" %>

<h1>予約内容の一覧</h1>

<% @reservations.each do |reservation| %>
 <table class="show-table">
　 </tr>
     <th>施設画像</th>
      <% if reservation.room.image?%>
      <td><%= image_tag reservation.room.image.to_s %></td>
      <% else %>
      <td><%= image_tag 'default-image.png' %></td>
      <%end%>
   </tr>
   </tr>
     <th>施設名</th>
     <td><%= reservation.room.title %></td>
   </tr>
   </tr>
     <th>紹介文</th>
     <td><%= reservation.room.content %></td>
   </tr>
　 </tr>
     <th>合計料金</th>
     <td><%= reservation.total_fee %></td>
   </tr>
   <tr>
     <th>チェックイン</th>
     <td><%= reservation.start_date.to_s(:datetime_jp) %></td>
   </tr>
   <tr>
     <th>チェックアウト</th>
     <td><%= reservation.end_date.to_s(:datetime_jp) %></td>
   </tr>
     <th>予約確定日時</th>
     <td><%= reservation.created_at.to_s(:default) %></td>
   </tr>
    <tr>
     <th>削除</th>
     <td><%= link_to '削除', reservation, method: :delete, data:{ confirm: "本当に削除しますか？"} %> </td>
   </tr>
 </table>
 <% end %>
<%= render "shared/footer"%>

app/views/rooms/create.html.erb
<h1>Rooms#create</h1>
<p>Find me in app/views/rooms/create.html.erb</p>

app/views/rooms/edit.html.erb
<%= render  "shared/navbar" %>
<h1>編集</h1>
<%= form_for @room do |f| %>
<table class="new-table">
    <tr>
        <th><%= f.label :title ,"施設名" %></th>
        <td><%= f.text_field :title %></td>
    <tr>
        <th><%= f.label :content ,"施設詳細" %></th>
        <td><%= f.text_field :content %></td>
    </tr>
    <tr>
        <th><%= f.label :fee ,"料金" %></th>
        <td><%= f.number_field :fee %></td>
    </tr>
    <tr class="checkbox">
        <th><%= f.label :address,"住所" %></th>
        <td><%= f.text_field :address %></td>
        <td>
        </td>
    </tr>
    <tr>
        <th><%= f.label :image ,"施設画像" %></th>
        <td><%= f.file_field :image %></td>
    </tr>
</table>
   
   <div>
       <ul>
           <li><%= link_to "キャンセル", :rooms %></li>
           <li><%= f.submit "保存" %></li>
       </ul>
   </div>
<% end %>
<%= render "shared/footer"%>

app/views/rooms/index.html.erb
<%= render  "shared/navbar" %>
<%= render  "shared/area" %>


<h1>rooms/index</h1>
<div class="count">
    <p><%= @rooms.count %>件が見つかりました</p>
</div>
<% @rooms.each do |room| %>

 <table class="show-table">
   <tr>
     <th>施設名</th>
     <td><%=link_to room.title, room_path(room.id) %></td>
   </tr>
   <tr>
     <th>住所</th>
     <td><%= room.address %></td>
   </tr>
   <tr>
     <th>施設詳細</th>
     <td><%= room.content %></td>
   </tr>
   <tr>
     <th>料金</th>
     <td><%= room.fee %></td>
   </tr>
     <th>画像</th>
     <td><%= image_tag room.image.to_s %></td>
   </tr>
    <tr>
     <th></th>
     <td><%=link_to "詳細はこちら", room_path(room.id) %></td>
   <tr>
 </table>
<% end %>
<%= render "shared/footer"%>

app/views/rooms/new.html.erb
<%= render  "shared/navbar" %>

<%= form_for @room do |f| %>
<table class="new-table">
    <tr>
        <th><%= f.label :title ,"施設名" %></th>
        <td><%= f.text_field :title %></td>
    <tr>
        <th><%= f.label :content ,"施設詳細" %></th>
        <td><%= f.text_field :content %></td>
    </tr>
    <tr>
        <th><%= f.label :fee ,"料金" %></th>
        <td><%= f.number_field :fee %></td>
    </tr>
    <tr class="checkbox">
        <th><%= f.label :address,"住所" %></th>
        <td><%= f.text_field :address %></td>
        <td>
        </td>
    </tr>
    <tr>
        <th><%= f.label :image ,"施設画像" %></th>
        <td><%= f.file_field :image %></td>
    </tr>
</table>
   
   <div>
       <ul>
           <li><%= link_to "キャンセル", :rooms %></li>
           <li><%= f.submit "保存" %></li>
       </ul>
   </div>
<% end %>
<%= render "shared/footer"%>

app/views/rooms/own.html.erb
<%= render  "shared/navbar" %>
 <h1>登録済み一覧</h1>
<% @rooms.each do |room| %>

 <table class="show-table">
   </tr>
     <th>画像</th>
      <% if room.image?%>
      <td><%= image_tag room.image.to_s %></td>
      <% else %>
      <td><%= image_tag 'default-image.png' %></td>
      <%end%>
   </tr>
   <tr>
     <th>施設名</th>
     <td><%=link_to room.title, room_path(room.id) %></td>
   </tr>
   <tr>
     <th>施設紹介</th>
     <td><%= room.content %></td>
   </tr>
   <tr>
     <th>宿泊料金</th>
     <td><%= room.fee %></td>
    <tr>
     <th>作成日</th>
     <td><%= room.created_at %></td>
   </tr>
    <tr>
     <th>編集</th>
     <td><%= link_to '編集', edit_room_path(room.id) %> </td>
   </tr>
   <tr>
     <th>削除</th>
     <td><%= link_to '削除', room, method: :delete, data:{ confirm: "本当に削除しますか？"} %> </td>
   </tr>
 </table>
<% end %>
<%= render "shared/footer"%>

app/views/rooms/show.html.erb
<%= render "shared/navbar"%>


<section>

 <table class="show-table">
   <tr>
     <th>施設名</th>
     <td><%= @room.title %></td>
   </tr>
   <tr>
     <th>施設詳細</th>
     <td><%=@room.content %></td>
   </tr>
   <tr>
     <th>料金</th>
     <td><%= @room.fee %></td>
   </tr>
   <tr>
     <th>住所</th>
     <td><%= @room.address %></td>
   </tr>
   <tr>
     <th>画像</th>
      <% if @room.image?%>
      <td><%= image_tag @room.image.to_s %></td>
      <% else %>
      <td><%= image_tag 'default-image.png' %></td>
      <%end%>
   </tr>
 </table>


<h1>予約フォーム</h1>
<%= render "shared/error", obj: @reservations %>


<%= form_with model:@reservation, local: true, url: confirm_reservation_path do |f| %>

	<dl>
		<dt>チェックイン</dt>
		<dd><%= f.date_field :start_date %></dd>
		<dt>チェックアウト</dt>
		<dd><%= f.date_field :end_date %></dd>
		<dt>人数</dt>
		<dd><%= f.number_field :total_people %></dd>
	</dl>
	 <dd><%= f.hidden_field :user_id, value: @user.id %></dd>
  <dd><%= f.hidden_field :room_id, value: @room.id%></dd>

	<%= f.submit '確認画面へ' %>
<% end %>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', new_room_path(@room) %>
 
 </section>
<%= render "shared/footer"%>

app/views/shared/_area.html.erb
<div>
    <%= form_with url: rooms_path, local: true, method: :get do |f|%>
　　<%= label_tag :address, 'エリア' %>
    <%= f.text_field :address, placeholder: "エリア" %>
    <%= f.text_field :keyword, placeholder: "キーワード" %>
    <%= f.submit "検索"%>
    <% end %>
</div>

app/views/shared/_error.html.erb
 <% if obj.errors.any? %>
   <% obj.errors.full_messages.each do |message| %>
     <ul>
       <li><%= message %></li>
     </ul>
   <% end %>
 <% end %>

app/views/shared/_footer.html.erb
<footer>
<h2>Potepan Share</h2>
<p>Copyright © Potepan Share 2023 All rights reserved</p>
</footer>

app/views/shared/_navbar.html.erb
<% if user_signed_in? %> 
<header class="nav-bar">
  <div class="left-header">
    <p><%= link_to "Potepan Share", root_path , class: "left-header_url"%></p>
  </div>
  <div class="right-header">
    <div class="header-icon">
      <% if current_user.avator?%>
      <p><%= image_tag current_user.avator.to_s, style: "border-radius: 50%; width: 70px; height: 70px; object-fit:cover;" %></p>
      <% else %>
      <p><%= image_tag 'default-avator.png', style: "border-radius: 50%; width: 70px; height: 70px; object-fit:cover;"  %></p>
      <%end%>
    </div>
    <div class="nav-content">
      <label for="toggle" onclick=""  for="menuToggle"><%= current_user.name%></label>  
      <input type="checkbox" id="toggle" autocomplete="off">
      <ul id="menu">
      <li class="dropdown__list"><%= link_to "施設の新規登録", new_room_path, class: "dropdown__list__url"%></li>
      <li class="dropdown__list"><%= link_to "予約済み一覧", reservations_path , class: "dropdown__list__url"%></li>
      <li class="dropdown__list"><%= link_to "登録済み一覧", rooms_own_path , class: "dropdown__list__url"%></li>
      <li class="dropdown__list"><%= link_to "アカウント設定", users_account_path , class: "dropdown__list__url"%> </li>
      <li class="dropdown__list"><%= link_to "ログアウト", destroy_user_session_path, method: :delete , class: "dropdown__list__url"%></li>
      </ul>
    </div>
  </div>
</header>
<% else %>
<header class="nav-bar">
  <div class="left-header">
    <p><%= link_to "Potepan Share", root_path , class: "left-header_url"%></p>
  </div>
  <div class="right-nonlogin-header">
  <p class="login"><%= link_to "ログイン", new_user_session_path , class: "login_url"%> </p>
  <p class="register"><%= link_to "新規登録", new_user_registration_path , class: "sign_in_url"%> </p>
  </div>
</header>
<% end %>

app/views/shared/_search.html.erb
<div>
    <%= form_with url: search_path, local: true, method: :get do |f|%>
　　<%= label_tag :address, 'エリア' %>
    <%= f.text_field :address %>
    <%= f.submit "検索"%>
    <% end %>
</div>

app/views/users/account.html.erb
<%= render "shared/navbar" %>
<h1>アカウント</h1>
 <table class="show-table">
   <tr>
     <th>メールアドレス</th>
     <td><%= @user.email %></td>
   </tr>
   <tr>
     <th>パスワード</th>
     <td>*********</td>
   </tr>
   <%= link_to "編集", edit_user_registration_path %>
   <%= link_to "プロフィール", users_profile_path %>

 </table>
 <%= render "shared/footer"%>

app/views/users/edit.html.erb
<%= render  "shared/navbar" %>
<%= link_to "アカウント", users_account_path %>
<%= link_to "プロフィール", users_profile_path %>

<h1>編集</h1>
<%= form_for @user do |f| %>
<table class="new-table">
    <tr>
        <th><%= f.label :avator ,"アイコン画像" %></th>
        <td><%= f.file_field :avator %></td>
    <tr>
        <th><%= f.label :name ,"名前" %></th>
        <td><%= f.text_field :name %></td>
    </tr>
    <tr>
        <th><%= f.label :profile ,"自己紹介" %></th>
        <td><%= f.text_field :profile%></td>
    </tr>
</table>
   
   <div>
       <ul>
           <li><%= link_to "キャンセル", users_profile_path %></li>
           <li><%= f.submit "保存" %></li>
       </ul>
   </div>
<% end %>
<%= render "shared/footer"%>

app/views/users/profile.html.erb
<%= render "shared/navbar" %>
 <h1>プロフィール</h1>
 <table class="show-table">
   <tr>
     <th>アイコン画像</th>
     <td><%= image_tag @user.avator.to_s, style: "border-radius: 50%; width: 70px; height: 70px; object-fit:cover;"%></td>
   </tr>
   <tr>
     <th>名前</th>
     <td><%= @user.name %></td>
   </tr>
   <tr>
     <th>自己紹介</th>
     <td><%= @user.profile %></td>
   </tr>
   <%= link_to "編集", edit_user_path(@user) %>
   <%= link_to "アカウント", users_account_path %>
 </table>
 <%= render "shared/footer"%>